version: "2"

linters:
  settings:
    staticcheck:
      checks:
        - all
        - -QF1003
        - -QF1012
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
