// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: recur/v1/recur.proto

package recurv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecurService_RegisterRecurfile_FullMethodName   = "/recur.v1.RecurService/RegisterRecurfile"
	RecurService_VerifyRecurfile_FullMethodName     = "/recur.v1.RecurService/VerifyRecurfile"
	RecurService_DeregisterRecurfile_FullMethodName = "/recur.v1.RecurService/DeregisterRecurfile"
	RecurService_ListPlugins_FullMethodName         = "/recur.v1.RecurService/ListPlugins"
	RecurService_ListTriggers_FullMethodName        = "/recur.v1.RecurService/ListTriggers"
	RecurService_ListActions_FullMethodName         = "/recur.v1.RecurService/ListActions"
	RecurService_ListGroups_FullMethodName          = "/recur.v1.RecurService/ListGroups"
	RecurService_ListRecurfiles_FullMethodName      = "/recur.v1.RecurService/ListRecurfiles"
	RecurService_InstallPlugin_FullMethodName       = "/recur.v1.RecurService/InstallPlugin"
	RecurService_UninstallPlugin_FullMethodName     = "/recur.v1.RecurService/UninstallPlugin"
	RecurService_GetConfig_FullMethodName           = "/recur.v1.RecurService/GetConfig"
	RecurService_SetConfig_FullMethodName           = "/recur.v1.RecurService/SetConfig"
	RecurService_DeleteConfig_FullMethodName        = "/recur.v1.RecurService/DeleteConfig"
	RecurService_GetStatus_FullMethodName           = "/recur.v1.RecurService/GetStatus"
	RecurService_InspectEntity_FullMethodName       = "/recur.v1.RecurService/InspectEntity"
	RecurService_SuspendEntity_FullMethodName       = "/recur.v1.RecurService/SuspendEntity"
	RecurService_ResumeEntity_FullMethodName        = "/recur.v1.RecurService/ResumeEntity"
	RecurService_TestEntity_FullMethodName          = "/recur.v1.RecurService/TestEntity"
	RecurService_ReportTriggerEvent_FullMethodName  = "/recur.v1.RecurService/ReportTriggerEvent"
)

// RecurServiceClient is the client API for RecurService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RecurService is the gRPC API for the recur daemon.
type RecurServiceClient interface {
	// Recurfile operations
	RegisterRecurfile(ctx context.Context, in *RegisterRecurfileRequest, opts ...grpc.CallOption) (*RegisterRecurfileResponse, error)
	VerifyRecurfile(ctx context.Context, in *VerifyRecurfileRequest, opts ...grpc.CallOption) (*VerifyRecurfileResponse, error)
	DeregisterRecurfile(ctx context.Context, in *DeregisterRecurfileRequest, opts ...grpc.CallOption) (*DeregisterRecurfileResponse, error)
	// List operations
	ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error)
	ListTriggers(ctx context.Context, in *ListTriggersRequest, opts ...grpc.CallOption) (*ListTriggersResponse, error)
	ListActions(ctx context.Context, in *ListActionsRequest, opts ...grpc.CallOption) (*ListActionsResponse, error)
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	ListRecurfiles(ctx context.Context, in *ListRecurfilesRequest, opts ...grpc.CallOption) (*ListRecurfilesResponse, error)
	// Plugin management
	InstallPlugin(ctx context.Context, in *InstallPluginRequest, opts ...grpc.CallOption) (*InstallPluginResponse, error)
	UninstallPlugin(ctx context.Context, in *UninstallPluginRequest, opts ...grpc.CallOption) (*UninstallPluginResponse, error)
	// Config operations
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
	DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error)
	// Daemon status
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Unified entity operations
	InspectEntity(ctx context.Context, in *InspectEntityRequest, opts ...grpc.CallOption) (*InspectEntityResponse, error)
	SuspendEntity(ctx context.Context, in *SuspendEntityRequest, opts ...grpc.CallOption) (*SuspendEntityResponse, error)
	ResumeEntity(ctx context.Context, in *ResumeEntityRequest, opts ...grpc.CallOption) (*ResumeEntityResponse, error)
	TestEntity(ctx context.Context, in *TestEntityRequest, opts ...grpc.CallOption) (*TestEntityResponse, error)
	// Plugin callback
	ReportTriggerEvent(ctx context.Context, in *ReportTriggerEventRequest, opts ...grpc.CallOption) (*ReportTriggerEventResponse, error)
}

type recurServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecurServiceClient(cc grpc.ClientConnInterface) RecurServiceClient {
	return &recurServiceClient{cc}
}

func (c *recurServiceClient) RegisterRecurfile(ctx context.Context, in *RegisterRecurfileRequest, opts ...grpc.CallOption) (*RegisterRecurfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterRecurfileResponse)
	err := c.cc.Invoke(ctx, RecurService_RegisterRecurfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) VerifyRecurfile(ctx context.Context, in *VerifyRecurfileRequest, opts ...grpc.CallOption) (*VerifyRecurfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyRecurfileResponse)
	err := c.cc.Invoke(ctx, RecurService_VerifyRecurfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) DeregisterRecurfile(ctx context.Context, in *DeregisterRecurfileRequest, opts ...grpc.CallOption) (*DeregisterRecurfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterRecurfileResponse)
	err := c.cc.Invoke(ctx, RecurService_DeregisterRecurfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPluginsResponse)
	err := c.cc.Invoke(ctx, RecurService_ListPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) ListTriggers(ctx context.Context, in *ListTriggersRequest, opts ...grpc.CallOption) (*ListTriggersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTriggersResponse)
	err := c.cc.Invoke(ctx, RecurService_ListTriggers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) ListActions(ctx context.Context, in *ListActionsRequest, opts ...grpc.CallOption) (*ListActionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActionsResponse)
	err := c.cc.Invoke(ctx, RecurService_ListActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, RecurService_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) ListRecurfiles(ctx context.Context, in *ListRecurfilesRequest, opts ...grpc.CallOption) (*ListRecurfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecurfilesResponse)
	err := c.cc.Invoke(ctx, RecurService_ListRecurfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) InstallPlugin(ctx context.Context, in *InstallPluginRequest, opts ...grpc.CallOption) (*InstallPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallPluginResponse)
	err := c.cc.Invoke(ctx, RecurService_InstallPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) UninstallPlugin(ctx context.Context, in *UninstallPluginRequest, opts ...grpc.CallOption) (*UninstallPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UninstallPluginResponse)
	err := c.cc.Invoke(ctx, RecurService_UninstallPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, RecurService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, RecurService_SetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConfigResponse)
	err := c.cc.Invoke(ctx, RecurService_DeleteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, RecurService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) InspectEntity(ctx context.Context, in *InspectEntityRequest, opts ...grpc.CallOption) (*InspectEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectEntityResponse)
	err := c.cc.Invoke(ctx, RecurService_InspectEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) SuspendEntity(ctx context.Context, in *SuspendEntityRequest, opts ...grpc.CallOption) (*SuspendEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendEntityResponse)
	err := c.cc.Invoke(ctx, RecurService_SuspendEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) ResumeEntity(ctx context.Context, in *ResumeEntityRequest, opts ...grpc.CallOption) (*ResumeEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeEntityResponse)
	err := c.cc.Invoke(ctx, RecurService_ResumeEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) TestEntity(ctx context.Context, in *TestEntityRequest, opts ...grpc.CallOption) (*TestEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestEntityResponse)
	err := c.cc.Invoke(ctx, RecurService_TestEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recurServiceClient) ReportTriggerEvent(ctx context.Context, in *ReportTriggerEventRequest, opts ...grpc.CallOption) (*ReportTriggerEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTriggerEventResponse)
	err := c.cc.Invoke(ctx, RecurService_ReportTriggerEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecurServiceServer is the server API for RecurService service.
// All implementations must embed UnimplementedRecurServiceServer
// for forward compatibility.
//
// RecurService is the gRPC API for the recur daemon.
type RecurServiceServer interface {
	// Recurfile operations
	RegisterRecurfile(context.Context, *RegisterRecurfileRequest) (*RegisterRecurfileResponse, error)
	VerifyRecurfile(context.Context, *VerifyRecurfileRequest) (*VerifyRecurfileResponse, error)
	DeregisterRecurfile(context.Context, *DeregisterRecurfileRequest) (*DeregisterRecurfileResponse, error)
	// List operations
	ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error)
	ListTriggers(context.Context, *ListTriggersRequest) (*ListTriggersResponse, error)
	ListActions(context.Context, *ListActionsRequest) (*ListActionsResponse, error)
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	ListRecurfiles(context.Context, *ListRecurfilesRequest) (*ListRecurfilesResponse, error)
	// Plugin management
	InstallPlugin(context.Context, *InstallPluginRequest) (*InstallPluginResponse, error)
	UninstallPlugin(context.Context, *UninstallPluginRequest) (*UninstallPluginResponse, error)
	// Config operations
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	DeleteConfig(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error)
	// Daemon status
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Unified entity operations
	InspectEntity(context.Context, *InspectEntityRequest) (*InspectEntityResponse, error)
	SuspendEntity(context.Context, *SuspendEntityRequest) (*SuspendEntityResponse, error)
	ResumeEntity(context.Context, *ResumeEntityRequest) (*ResumeEntityResponse, error)
	TestEntity(context.Context, *TestEntityRequest) (*TestEntityResponse, error)
	// Plugin callback
	ReportTriggerEvent(context.Context, *ReportTriggerEventRequest) (*ReportTriggerEventResponse, error)
	mustEmbedUnimplementedRecurServiceServer()
}

// UnimplementedRecurServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecurServiceServer struct{}

func (UnimplementedRecurServiceServer) RegisterRecurfile(context.Context, *RegisterRecurfileRequest) (*RegisterRecurfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterRecurfile not implemented")
}
func (UnimplementedRecurServiceServer) VerifyRecurfile(context.Context, *VerifyRecurfileRequest) (*VerifyRecurfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyRecurfile not implemented")
}
func (UnimplementedRecurServiceServer) DeregisterRecurfile(context.Context, *DeregisterRecurfileRequest) (*DeregisterRecurfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterRecurfile not implemented")
}
func (UnimplementedRecurServiceServer) ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlugins not implemented")
}
func (UnimplementedRecurServiceServer) ListTriggers(context.Context, *ListTriggersRequest) (*ListTriggersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTriggers not implemented")
}
func (UnimplementedRecurServiceServer) ListActions(context.Context, *ListActionsRequest) (*ListActionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActions not implemented")
}
func (UnimplementedRecurServiceServer) ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedRecurServiceServer) ListRecurfiles(context.Context, *ListRecurfilesRequest) (*ListRecurfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecurfiles not implemented")
}
func (UnimplementedRecurServiceServer) InstallPlugin(context.Context, *InstallPluginRequest) (*InstallPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallPlugin not implemented")
}
func (UnimplementedRecurServiceServer) UninstallPlugin(context.Context, *UninstallPluginRequest) (*UninstallPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UninstallPlugin not implemented")
}
func (UnimplementedRecurServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedRecurServiceServer) SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedRecurServiceServer) DeleteConfig(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConfig not implemented")
}
func (UnimplementedRecurServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedRecurServiceServer) InspectEntity(context.Context, *InspectEntityRequest) (*InspectEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectEntity not implemented")
}
func (UnimplementedRecurServiceServer) SuspendEntity(context.Context, *SuspendEntityRequest) (*SuspendEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendEntity not implemented")
}
func (UnimplementedRecurServiceServer) ResumeEntity(context.Context, *ResumeEntityRequest) (*ResumeEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeEntity not implemented")
}
func (UnimplementedRecurServiceServer) TestEntity(context.Context, *TestEntityRequest) (*TestEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestEntity not implemented")
}
func (UnimplementedRecurServiceServer) ReportTriggerEvent(context.Context, *ReportTriggerEventRequest) (*ReportTriggerEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTriggerEvent not implemented")
}
func (UnimplementedRecurServiceServer) mustEmbedUnimplementedRecurServiceServer() {}
func (UnimplementedRecurServiceServer) testEmbeddedByValue()                      {}

// UnsafeRecurServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecurServiceServer will
// result in compilation errors.
type UnsafeRecurServiceServer interface {
	mustEmbedUnimplementedRecurServiceServer()
}

func RegisterRecurServiceServer(s grpc.ServiceRegistrar, srv RecurServiceServer) {
	// If the following call panics, it indicates UnimplementedRecurServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecurService_ServiceDesc, srv)
}

func _RecurService_RegisterRecurfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRecurfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).RegisterRecurfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_RegisterRecurfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).RegisterRecurfile(ctx, req.(*RegisterRecurfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_VerifyRecurfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRecurfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).VerifyRecurfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_VerifyRecurfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).VerifyRecurfile(ctx, req.(*VerifyRecurfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_DeregisterRecurfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRecurfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).DeregisterRecurfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_DeregisterRecurfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).DeregisterRecurfile(ctx, req.(*DeregisterRecurfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_ListPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).ListPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_ListPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).ListPlugins(ctx, req.(*ListPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_ListTriggers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTriggersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).ListTriggers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_ListTriggers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).ListTriggers(ctx, req.(*ListTriggersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_ListActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).ListActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_ListActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).ListActions(ctx, req.(*ListActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_ListRecurfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecurfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).ListRecurfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_ListRecurfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).ListRecurfiles(ctx, req.(*ListRecurfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_InstallPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).InstallPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_InstallPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).InstallPlugin(ctx, req.(*InstallPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_UninstallPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).UninstallPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_UninstallPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).UninstallPlugin(ctx, req.(*UninstallPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_DeleteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).DeleteConfig(ctx, req.(*DeleteConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_InspectEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).InspectEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_InspectEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).InspectEntity(ctx, req.(*InspectEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_SuspendEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).SuspendEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_SuspendEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).SuspendEntity(ctx, req.(*SuspendEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_ResumeEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).ResumeEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_ResumeEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).ResumeEntity(ctx, req.(*ResumeEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_TestEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).TestEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_TestEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).TestEntity(ctx, req.(*TestEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecurService_ReportTriggerEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTriggerEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecurServiceServer).ReportTriggerEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecurService_ReportTriggerEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecurServiceServer).ReportTriggerEvent(ctx, req.(*ReportTriggerEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecurService_ServiceDesc is the grpc.ServiceDesc for RecurService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecurService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recur.v1.RecurService",
	HandlerType: (*RecurServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterRecurfile",
			Handler:    _RecurService_RegisterRecurfile_Handler,
		},
		{
			MethodName: "VerifyRecurfile",
			Handler:    _RecurService_VerifyRecurfile_Handler,
		},
		{
			MethodName: "DeregisterRecurfile",
			Handler:    _RecurService_DeregisterRecurfile_Handler,
		},
		{
			MethodName: "ListPlugins",
			Handler:    _RecurService_ListPlugins_Handler,
		},
		{
			MethodName: "ListTriggers",
			Handler:    _RecurService_ListTriggers_Handler,
		},
		{
			MethodName: "ListActions",
			Handler:    _RecurService_ListActions_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _RecurService_ListGroups_Handler,
		},
		{
			MethodName: "ListRecurfiles",
			Handler:    _RecurService_ListRecurfiles_Handler,
		},
		{
			MethodName: "InstallPlugin",
			Handler:    _RecurService_InstallPlugin_Handler,
		},
		{
			MethodName: "UninstallPlugin",
			Handler:    _RecurService_UninstallPlugin_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _RecurService_GetConfig_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _RecurService_SetConfig_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _RecurService_DeleteConfig_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _RecurService_GetStatus_Handler,
		},
		{
			MethodName: "InspectEntity",
			Handler:    _RecurService_InspectEntity_Handler,
		},
		{
			MethodName: "SuspendEntity",
			Handler:    _RecurService_SuspendEntity_Handler,
		},
		{
			MethodName: "ResumeEntity",
			Handler:    _RecurService_ResumeEntity_Handler,
		},
		{
			MethodName: "TestEntity",
			Handler:    _RecurService_TestEntity_Handler,
		},
		{
			MethodName: "ReportTriggerEvent",
			Handler:    _RecurService_ReportTriggerEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recur/v1/recur.proto",
}
