name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.66.0"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate protobuf
        working-directory: api
        run: buf generate

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
          args: ./src/... ./plugins/calendar/... ./plugins/devicemonitor/... ./plugins/mqtt/... ./plugins/timer/... ./plugins/webhook/...

  proto-lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v7

      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.66.0"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Buf lint
        working-directory: api
        run: buf lint

      - name: Buf breaking change detection
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: api
          against: "https://github.com/${{ github.repository }}.git#branch=${{ github.base_ref }},subdir=api"
